# Generated by Django 5.1.15 on 2026-02-22 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'db_table': 'inventory_stock',
            },
        ),
    ]
