# Generated by Django 5.1.15 on 2025-12-22 16:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(default=0)),
                ("reserved", models.IntegerField(default=0)),
                ("product_id", models.UUIDField(unique=True, db_index=True)),
            ],
            options={
                "db_table": "inventory_stock",
                "verbose_name": "Stock",
                "verbose_name_plural": "Stock",
            },
        ),
    ]
