# Generated by Django 5.1.15 on 2026-01-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stock",
            name="inventory_stock_quantity_check",
        ),
        migrations.RemoveConstraint(
            model_name="stock",
            name="inventory_stock_reserved_check",
        ),
        migrations.RemoveIndex(
            model_name="stock",
            name="idx_inventory_stock_product_id",
        ),
    ]
