# Generated by Django 5.1.15 on 2026-01-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="quoterequest",
            name="idx_quotes_request_status",
        ),
        migrations.RemoveIndex(
            model_name="quoterequest",
            name="idx_quotes_request_email",
        ),
    ]
