# Generated by Django 5.1.15 on 2026-02-22 18:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('warranty_duration_months', models.IntegerField(default=12)),
                ('expiry_date', models.DateField()),
                ('is_valid', models.BooleanField(default=True)),
                ('support_level', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=50)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'db_table': 'warranty_warrantycheck',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
