# Generated by Django 5.1.15 on 2025-12-22 16:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WarrantyCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("product_name", models.CharField(max_length=255)),
                ("product_category", models.CharField(max_length=100)),
                ("purchase_date", models.DateField()),
                ("warranty_duration_months", models.IntegerField(default=12)),
                ("expiry_date", models.DateField()),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "support_level",
                    models.CharField(
                        max_length=50,
                        choices=[
                            ("basic", "Basic"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        default="standard",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255, blank=True)),
                ("customer_email", models.EmailField(max_length=255, blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={"db_table": "warranty_warrantycheck", "ordering": ["-created_at"]},
        ),
    ]
