# Generated by Django 5.1.15 on 2026-01-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warranty", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="warrantycheck",
            name="idx_warranty_serial",
        ),
        migrations.RemoveIndex(
            model_name="warrantycheck",
            name="idx_warranty_expiry",
        ),
        migrations.RemoveIndex(
            model_name="warrantycheck",
            name="idx_warranty_email",
        ),
    ]
