# Generated by Django 5.1.15 on 2026-01-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="blogpost",
            name="idx_blog_blogpost_category_id",
        ),
        migrations.RemoveIndex(
            model_name="blogpost",
            name="idx_blog_blogpost_published_at",
        ),
        migrations.RemoveIndex(
            model_name="blogpost",
            name="idx_blog_blogpost_is_published",
        ),
        migrations.RemoveIndex(
            model_name="blogpost",
            name="idx_blog_blogpost_slug",
        ),
    ]
