# Generated by Django 5.1.15 on 2025-12-22 16:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        # Cart Model
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(unique=True, db_index=True)),
            ],
            options={
                "db_table": "cart_cart",
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
        # CartItem Model
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("cart_id", models.UUIDField(db_index=True)),
                ("product_id", models.UUIDField(db_index=True)),
            ],
            options={
                "db_table": "cart_cartitem",
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
                "ordering": ["-created_at"],
            },
        ),
        # Unique constraint for cart_id + product_id
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=["cart_id", "product_id"], name="unique_cart_product"
            ),
        ),
    ]
