# Generated by Django 5.1.15 on 2026-01-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cart",
            name="idx_cart_cart_user_id",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="idx_cart_cartitem_cart_id",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="idx_cart_cartitem_product_id",
        ),
    ]
