# Generated by Django 5.1.15 on 2026-01-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_remove_cart_idx_cart_cart_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user_id__isnull", False)),
                fields=("user_id",),
                name="unique_user_cart",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key__isnull", False)),
                fields=("session_key",),
                name="unique_session_cart",
            ),
        ),
    ]
