# Generated by Django 5.1.15 on 2026-01-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_supabase_jwt_role_sync"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casestudy",
            options={
                "ordering": ["-project_date", "-is_featured"],
                "verbose_name_plural": "Case Studies",
            },
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="idx_core_userprofile_supabase_id",
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="idx_core_userprofile_email",
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="idx_core_userprofile_role",
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="order",
            field=models.IntegerField(default=0, help_text="Display order"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=50,
            ),
        ),
    ]
