export declare function useProductsPage(): {
    products: any;
    isLoading: boolean;
    totalCount: any;
    totalPages: number;
    currentPage: number;
    perPage: number;
    hasNext: boolean;
    hasPrevious: boolean;
    searchInput: string;
    categoryFilter: string;
    selectedIds: string[];
    categories: import("../types").Category[];
    handleSearch: (e: React.FormEvent) => void;
    handleSearchInputChange: (value: string) => void;
    handleCategoryChange: (category: string) => void;
    handlePageChange: (page: number) => void;
    handlePageSizeChange: (newSize: string) => void;
    handleSelectRow: (productId: string, checked: boolean) => void;
    handleSelectAll: (checked: boolean) => void;
    handleClearSelection: () => void;
    handleDelete: (slug: string) => Promise<void>;
    handleDuplicate: (slug: string) => void;
    handleBulkDelete: (ids: string[]) => Promise<void>;
    handleBulkActivate: (ids: string[]) => Promise<void>;
    handleBulkDeactivate: (ids: string[]) => Promise<void>;
    isAllSelected: boolean;
    isSomeSelected: boolean;
};
