# Generated by Django 5.1.15 on 2026-01-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contactsubmission",
            name="idx_contacts_submission_is_read",
        ),
        migrations.RemoveIndex(
            model_name="contactsubmission",
            name="idx_contacts_submission_email",
        ),
    ]
