# Generated by Django 5.1.15 on 2026-01-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="idx_orders_order_user_id",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="idx_orders_order_status",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="idx_orders_order_created_at",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="idx_orders_orderitem_order_id",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="idx_orders_orderitem_product_id",
        ),
    ]
