# Generated by Django 5.1.15 on 2025-12-22 16:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(max_length=255, db_index=True)),
                ("user_email", models.EmailField(max_length=255)),
                ("rating", models.SmallIntegerField()),
                ("comment", models.TextField()),
                ("is_verified_purchase", models.BooleanField(default=False)),
                ("product_id", models.UUIDField(db_index=True)),
            ],
            options={
                "db_table": "reviews_review",
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_at"],
            },
        ),
        # Add constraint for unique user per product
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=["user_id", "product_id"], name="unique_user_product_review"
            ),
        ),
    ]
