# Generated by Django 5.1.15 on 2026-01-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="reviews_review_rating_check",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="idx_reviews_review_product_id",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="idx_reviews_review_rating",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="idx_reviews_review_created_at",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="idx_reviews_review_user_id",
        ),
    ]
