# Generated by Django 5.1.15 on 2026-01-14 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_remove_review_reviews_review_rating_check_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="helpful_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="review",
            name="not_helpful_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="ReviewVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("user_email", models.EmailField(max_length=255)),
                ("is_helpful", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        db_column="review_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Vote",
                "verbose_name_plural": "Review Votes",
                "db_table": "review_votes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("review", "user_email"),
                        name="unique_review_vote_per_user",
                    )
                ],
            },
        ),
    ]
