# Generated by Django 5.1.15 on 2025-12-22 16:37


import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=255, unique=True)),
                ("amount", models.DecimalField(max_digits=10, decimal_places=2)),
                (
                    "status",
                    models.CharField(
                        max_length=50,
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="pending",
                    ),
                ),
                ("paystack_response", models.JSONField(null=True, blank=True)),
                ("order_id", models.UUIDField(db_index=True)),
            ],
            options={
                "db_table": "payments_payment",
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
