# Generated by Django 5.1.15 on 2026-01-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payment",
            name="idx_payments_payment_reference",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="idx_payments_payment_status",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="idx_payments_payment_created_at",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="idx_payments_payment_order_id",
        ),
    ]
