# Generated by Django 5.1.15 on 2025-12-22 16:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        # Category Model
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.URLField(blank=True, help_text="Supabase Storage URL"),
                ),
                ("parent_id", models.UUIDField(null=True, blank=True, db_index=True)),
            ],
            options={
                "db_table": "products_category",
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        # Product Model
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True, max_length=255)),
                ("description", models.TextField()),
                ("short_description", models.CharField(max_length=500, blank=True)),
                ("price", models.DecimalField(max_digits=10, decimal_places=2)),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original price for showing discounts",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "featured_image",
                    models.URLField(blank=True, help_text="Supabase Storage URL"),
                ),
                ("meta_title", models.CharField(max_length=255, blank=True)),
                ("meta_description", models.CharField(max_length=500, blank=True)),
                ("category_id", models.UUIDField(db_index=True)),
            ],
            options={
                "db_table": "products_product",
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
        # Product Image Model
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_url", models.URLField(help_text="Supabase Storage URL")),
                ("alt_text", models.CharField(max_length=255, blank=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("product_id", models.UUIDField(db_index=True)),
            ],
            options={
                "db_table": "products_productimage",
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["position", "created_at"],
            },
        ),
        # Product Specification Model
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        help_text="e.g., 'Wattage', 'Voltage'", max_length=100
                    ),
                ),
                (
                    "value",
                    models.CharField(help_text="e.g., '500W', '48V'", max_length=200),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("product_id", models.UUIDField(db_index=True)),
            ],
            options={
                "db_table": "products_productspecification",
                "verbose_name": "Product Specification",
                "verbose_name_plural": "Product Specifications",
                "ordering": ["position"],
            },
        ),
    ]
