# Generated by Django 5.1.15 on 2026-01-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["position"],
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="idx_products_category_slug",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="idx_products_product_slug",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="idx_products_product_is_active",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="idx_products_product_is_featured",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="idx_products_product_category_id",
        ),
        migrations.AddField(
            model_name="product",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="compare_at_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="featured_image",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="key",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="value",
            field=models.CharField(max_length=500),
        ),
    ]
