# Generated by Django 5.1.15 on 2026-02-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, default='Main Warehouse', max_length=255, null=True),
        ),
    ]
