# Generated by Django 5.1.15 on 2026-01-13 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_add_inventory_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_column="category_id",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="products",
                to="products.category",
            ),
        ),
    ]
