# Generated by Django 5.1.15 on 2026-03-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='target_stock',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
