# Generated by Django 5.1.15 on 2026-01-14 03:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_wishlist_alter_product_category_wishlistitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockNotification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=255)),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("is_notified", models.BooleanField(default=False)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_notifications",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Notification",
                "verbose_name_plural": "Stock Notifications",
                "db_table": "stock_notifications",
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "email"),
                        name="unique_product_email_notification",
                    )
                ],
            },
        ),
    ]
