# Generated by Django 5.1.15 on 2026-01-14 03:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_stocknotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductQuestion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(max_length=255)),
                ("question", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Question",
                "verbose_name_plural": "Product Questions",
                "db_table": "product_questions",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductAnswer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(max_length=255)),
                ("answer", models.TextField()),
                ("is_official", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_best_answer", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("helpful_count", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="products.productquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Answer",
                "verbose_name_plural": "Product Answers",
                "db_table": "product_answers",
                "ordering": ["-is_best_answer", "-helpful_count", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnswerVote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("user_email", models.EmailField(max_length=255)),
                (
                    "answer",
                    models.ForeignKey(
                        db_column="answer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="products.productanswer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer Vote",
                "verbose_name_plural": "Answer Votes",
                "db_table": "answer_votes",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("answer", "user_email"),
                        name="unique_answer_vote_per_user",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="productquestion",
            index=models.Index(
                fields=["product", "is_approved"], name="product_que_product_006d0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productanswer",
            index=models.Index(
                fields=["question", "is_approved"],
                name="product_ans_questio_82c3b5_idx",
            ),
        ),
    ]
