# Generated by Django 5.1.15 on 2026-01-14 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productquestion_productanswer_answervote_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("user_email", models.EmailField(blank=True, max_length=255)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("product_ids", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Comparison",
                "verbose_name_plural": "Product Comparisons",
                "db_table": "product_comparisons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("video_url", models.URLField(max_length=500)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Video",
                "verbose_name_plural": "Product Videos",
                "db_table": "product_videos",
                "ordering": ["-is_primary", "display_order", "-created_at"],
            },
        ),
    ]
