# Generated by Django 5.1.15 on 2026-01-14 03:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_productcomparison_productvideo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(blank=True, max_length=255)),
                ("product_id", models.UUIDField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_message_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "db_table": "chat_sessions",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(blank=True, max_length=255)),
                ("message", models.TextField()),
                ("is_staff_reply", models.BooleanField(default=False)),
                ("staff_name", models.CharField(blank=True, max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "chat_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "created_at"],
                        name="chat_messag_session_597c4e_idx",
                    )
                ],
            },
        ),
    ]
