# Generated by Django 5.1.15 on 2026-01-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_chatsession_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocknotification",
            name="admin_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="stocknotification",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="stocknotification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
